### ISSUE TITLE
ERROR: chatGPT_answer failed | becuase of not paid API access

### ISSUE THREAD

**Issue by sommersdev** [The-CodingSloth/kahoot-god#5]
I tried to use the script but as I clicked CTRL + ALT + T the Console says the Question and Anwers but then there is:
```
Something went wrong.
chatGPT_answer failed
```
and the API says at the API KEY: never used

can someone pls help me fix this?

**Comment by nateloeffel** [comment]
Can you take a screenshot of the code where you define your api key (you can blur or mark out the key)

**Comment by nateloeffel** [comment]
Be sure that you have defined the api key **inside** the quotes

**Comment by sommersdev** [comment]
Thank you for the quick responce here is the screenshot:
![grafik](https://github.com/The-CodingSloth/kahoot-god/assets/102815713/b98afe75-2ffb-46fe-ba62-535c0c9cb754)

**Comment by nateloeffel** [comment]
can you try rerunning it and taking a screenshot of more of the logs. just trying to figure to figure out what the issue is

**Comment by nateloeffel** [comment]
regarding the 0 uses thing on the api key, that can happen because openai takes a little bit to register everything

**Comment by nateloeffel** [comment]
try replacing this (lines 78-79):
```py
except:
    print("chatGPT_answer failed")
```
with this 
```py
except Exception as e:
    print(f"chatGPT_answer failed with error: {str(e)}")
```
so that we can see what the error is

**Comment by sommersdev** [comment]
The Error is:
```
Something went wrong.
chatGPT_answer failed with error: cannot access local variable 'response' where it is not associated with a value
```

**Comment by nateloeffel** [comment]
can you try setting your tesseract path to this? Not sure if it will work just a guess:
`C:\Program Files\Tesseract-OCR\tesseract.exe`

**Comment by sommersdev** [comment]
But the response Variable is the responce of `response = openai.ChatCompletion.create(model="gpt-4", messages=conversation)` that gets a value when the openai command gets ran

**Comment by nateloeffel** [comment]
right but since I dont see how that could be causing an error I'm just checking whats different between your code and mine since mine works

**Comment by sommersdev** [comment]
> can you try setting your tesseract path to this? Not sure if it will work just a guess: `C:\Program Files\Tesseract-OCR\tesseract.exe`

Tesseract gets the Question and Anwers, but the responce variable doesn´t get a value

**Comment by nateloeffel** [comment]
are you sure your api is correct then?

> > can you try setting your tesseract path to this? Not sure if it will work just a guess: `C:\Program Files\Tesseract-OCR\tesseract.exe`
> 
> Tesseract gets the Question and Anwers, but the responce variable doesn´t get a value

**Comment by sommersdev** [comment]
I have created a new API token but there is still the same error

**Comment by nateloeffel** [comment]
try changing 'gpt-4' to 'gpt-3.5-turbo'

**Comment by sommersdev** [comment]
same Error

**Comment by nateloeffel** [comment]
alr hold on ima send you my code exactly see if you get the same error

**Comment by sommersdev** [comment]
ok I´ll test it

**Comment by nateloeffel** [comment]
```py
import keyboard
import pyautogui
import pytesseract
import openai

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"  # Path to tesseract.exe example path: r"C:\Program Files\Tesseract-OCR\tesseract.exe"
openai.api_key = "sk-"


def click_button(button):
    # Coordinates for each button
    button_coords = {1: (579, 1040), 2: (1562, 1037), 3: (528, 1261), 4: (1803, 1255)}
    x, y = button_coords[button]
    pyautogui.click(x, y)


def chatGPT_answer(question_and_answers):
    # Adding explicit instruction to the prompt
    # Modify the instruction to the model to fit your needs
    conversation = [
        {
            "role": "system",
            "content": "You are a helpful assistant specialized in answering multiple-choice questions who only responds with the button number corresponding to the most likely answer do not respond with words only a integer. You'll do this even if the question involves content you can't analyze, such as videos or images. If you cannot answer the question, you'll respond with an educated guess. Remember only respond with an integer between 1 and 4 that corresponds to the answer.",
        },
        {"role": "user", "content": question_and_answers},
    ]
    try:
        response = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=conversation) # can be set to 'gpt-4' if needed

        # Extract the assistant's reply
        reply = response["choices"][0]["message"]["content"].strip()
        # Return the button number as an integer
        return int(reply)
    except ValueError:
        # Handle exception here if the reply is not an integer
        print(f"Unexpected reply: {reply}")
        return int(reply[0])
    except:
        # Handle exception here if something else goes wrong
        print("Something went wrong.")
        print(response)
        return None


def kahoot_god():
    # Coordinates for kahoot question and answers
    question_and_answers = {
        0: {"top_left": (0, 72), "bottom_right": (2475, 200)},
        1: {"top_left": (105, 1000), "bottom_right": (1219, 1118)},
        2: {"top_left": (1370, 1000), "bottom_right": (2500, 1127)},
        3: {"top_left": (100, 1200), "bottom_right": (1260, 1361)},
        4: {"top_left": (1370, 1175), "bottom_right": (2000, 1353)},
    }
    res = ""
    for element in question_and_answers:
        coords = question_and_answers[element]
        x1, y1 = coords["top_left"]
        x2, y2 = coords["bottom_right"]

        # Calculate width and height for each element for screenshot
        width = x2 - x1
        height = y2 - y1

        screenshot = pyautogui.screenshot(region=(x1, y1, width, height))
        screenshot_text = pytesseract.image_to_string(screenshot)
        if not screenshot_text.strip():
            print("No text detected.")
            continue
        if element == 0:
            res += f"Question: {screenshot_text}"
        else:
            res += f"{element}: {screenshot_text}"
    print(res)
    try:
        answer = chatGPT_answer(res)
        click_button(answer)
        print(f"Answer: {answer}")
    except:
        print("chatGPT_answer failed")


# Bind the function to a hotkey
keyboard.add_hotkey("ctrl+alt+t", kahoot_god)
# Keep the program running
keyboard.wait()
```

if you choose to use all 53 of my cents then go ahead

**Comment by sommersdev** [comment]
no, i´ll do just one request

**Comment by sommersdev** [comment]
My reselution settings broke, but it has functioned

**Comment by nateloeffel** [comment]
wdym ur resolution settings

**Comment by sommersdev** [comment]
could be thats your code and reselution settings
I am trying it on a 1080p screen

**Comment by nateloeffel** [comment]
now try adding that api key into your previous code

**Comment by sommersdev** [comment]
ok

**Comment by sommersdev** [comment]
still doesn´t worked
but where do you create the API key? on: https://platform.openai.com/account/api-keys right?

**Comment by nateloeffel** [comment]
yes

**Comment by nateloeffel** [comment]
try adding a print(response) line after you request the chatgpt completion

**Comment by sommersdev** [comment]
I think i found the problem with the responce. I thought I can use the API for free but you must pay it to use it. Thank you for your help
